[package]
name = "ludis-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
base64ct = "1.6.0"
russh.workspace = true
russh-sftp = "2.1.1"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
