[package]
name = "ludis-params"
version = "0.1.0"
edition = "2024"

[dependencies]
rimu-interop = { path = "../rimu-interop", version = "0.1" }
displaydoc.workspace = true
indexmap.workspace = true
rimu.workspace = true
serde.workspace = true
thiserror.workspace = true
