[package]
name = "avo-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.24", features = ["brotli", "gzip", "stream"] }
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream = "0.1.17"
toml = "0.9.8"
