[debian-13-x86-64]
arch = "x86-64"
os = { type = "linux", linux = "debian", debian = 13 }
image = { type = "qcow2", url = "https://cloud.debian.org/images/cloud/trixie/latest/debian-13-generic-amd64.qcow2" }
hash = { type = "sha512sums", url = "https://cloud.debian.org/images/cloud/trixie/latest/SHA512SUMS" }
kernel_root = "/dev/vda1"
user = "debian"
