pub struct Image {
    pub vendor: String,
    pub codename: String,
    pub version: String,
    pub arch: Arch,
    pub url: String,
    pub size: Option<u64>,
}

[debian-12-x86-64]
vendor = "Debian"
codename = "Bookworm"
version = "12"
arch = "x86-64"
image = { type = "qcow2", url = "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2" }
hash = { type = "sha512sums", url = "https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS" }
