[debian-12-x86-64]
arch = "x86-64"
os = { type = "Linux", linux = "Debian", debian = 13 }
image = { type = "qcow2", url = "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2" }
hash = { type = "sha512sums", url = "https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS" }
