[package]
name = "lusid-operation"
version = "0.1.0"
edition = "2024"

[dependencies]
lusid-cmd = { path = "../cmd", version = "0.1" }
lusid-view = { path = "../view", version = "0.1" }
async-trait.workspace = true
thiserror.workspace = true
tracing.workspace = true
